FROM golang:1.24-alpine as builder

COPY . /creek-pg-client
WORKDIR /creek-pg-client

RUN go mod download
RUN go build -o /clientd cmd/clientd.go

FROM --platform=linux/amd64 alpine:3.21.3

COPY --from=builder /clientd /
ENTRYPOINT [ "/clientd" ]