FROM golang:1.24

RUN apt-get update && apt-get install -y inotify-hookable
RUN go install github.com/codeskyblue/fswatch@latest

RUN mkdir -p /creek-pg-client
WORKDIR /creek-pg-client
EXPOSE 8080

CMD fswatch -config ./fsw.yml